version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/carimbo_db
      - SESSION_SECRET=your-secret-key-change-this
    depends_on:
      - db
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:5000 --reload main:app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=carimbo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: